# In this tutorial we will learn how to add indicators and signals to the strategy. 
# As this is an introduction tutorial and to keep it simple, we will build strategy for ‘long trade'(discussed in chapter 1) 
# only i.e., we buy first and later sell.

###########################################################################
## The strategy that we are going to use in this tutorial is as follows: ##
###########################################################################

## Enter the market when:
  # RSI7 value is greater than a threshold value of 50 & MACD histogram crosses the 0-line from below

## Exit the market when :
  # either RSI7 value is lesser than a threshold value of 50 or MACD histogram crosses the 0-line from above.



library(quantstrat)
Sys.setenv(TZ = "Asia/Kolkata")
currency('INR')

init_date <- "2011-12-31"
start_date <- "2012-01-01"
end_date <- "2017-12-31"
init_equity <- 100000
adjustment <- TRUE
getSymbols(Symbols = "^NSEI", 
           src = "yahoo", index.class = "POSIXct",
           from = start_date, 
           to = end_date, 
           adjust = adjustment)


knitr::kable(head(NSEI))

NSEI=na.omit(NSEI)
stock("NSEI",currency="INR",multiplier = 1)


# Strategy Setup --------------------------------------------------------------------------------------------------

strategy.st<-"basic_strat"
portfolio.st<-"basic_portfolio"
account.st<-"basic_account"
rm.strat(portfolio.st)
rm.strat(account.st)
initPortf(name = portfolio.st,symbols = "NSEI",initDate = init_date)


initAcct(name = account.st,portfolios = portfolio.st,initDate = init_date,initEq = init_equity)


initOrders(portfolio = portfolio.st,symbols = "NSEI",initDate = init_date)
strategy(strategy.st, store = TRUE)


# Add Indicators --------------------------------------------------------------------------------------------------

## In this strategy the indicators to be used are RSI and MACD. Let us add these indicators to the strategy-
  # add RSI for 7 day period as indicator to the strategy

add.indicator(strategy = strategy.st,
              name = "RSI",
              arguments = list(price = quote(Cl(mktdata)), 
                               n = 7),
              label = "RSI_7")

## Plot the RSI of closing prices with n=7 using Chartseries function and add a line at RSI=50.

chartSeries(RSI(NSEI$NSEI.Close,n=7),theme="black",name="RSI n=7")
abline(a=50,b=0,col="blue")



## add macd as indicator to the strategy, macd takes fastMA = 12, slowMA = 26, signalMA = 9

fastMA = 12 
slowMA = 26 
signalMA = 9
maType="EMA"
add.indicator(strategy.st, name = "MACD", 
              arguments = list(x=quote(Cl(mktdata)),
                               nFast=fastMA, 
                               nSlow=slowMA,histogram = TRUE),
              label='MACD' 
)


# Using chartseries function let us plot the MACD of NSEI closing prices where fast moving average is 
# taken for 12 day period, slow moving average is taken for 26 day period and 9 day period for signal moving average.

chartSeries(NSEI$NSEI.Close,TA="addMACD(fast = 12, slow = 26, signal = 9)",theme="black",name="MACD 26-12-9")



# apply indicator -------------------------------------------------------------------------------------------------

# applyIndicators 
# function is used to apply indicators specified in the strategy to the mkdata. Here mktdata is the NSEI data.


mktdata_ind <- applyIndicators(strategy=strategy.st,mktdata=NSEI)
mktdata_ind[is.na(mktdata_ind)]=0
knitr::kable(tail(mktdata_ind))




# Signal ----------------------------------------------------------------------------------------------------------
# Signal is a sign that tells whether it is time to buy or sell security. 
# Signals can be triggered either on the basis of technical indicators or time metrics or prices.



# add.signal 
# in quantstrat helps to add a signal to the trading strategy. The arguments of this function are:

  # strategy 
  # to which signal is to be added, 
  # name of the function used to generate signal, 
  # arguments of the function
  # label a text that will be used as name for the signal output.



# Functions to generate a signal:
#  i. sigThreshold
#      In trading strategies certain decisions are to be made when an indicator 
#      is greater than or less than a specific threshold value. 
#      sigThreshold function generates signal by returning true when an indicator crosses a 
#      threshold value by given relationship.

#      relationship can be greater than(gt), less than(lt), eq(equal to), 
#      greater than or equal to(gte) and less than or equal to(lte).



#  ii. sigCrossover
#      Sometimes trading signals are to be generated by comparing 2 indicators, for example you might want 
#      to generate a signal when macd line crosses the signal line from below for the first time. 
#      sigCrossover function generates signal by returning true when an indicator crosses other indicator by a 
#      given relationship for the first time.



#   iii. sigComparison
#      sigComparison function is similar to sigCrossover except that it returns true everytime when the 
#      relationship between 2 indicators holds true.



#   iv. sigFormula
#      In some situations you might want to generate a signal by comparing 2 or more columns. 
#      sigFormula function applies a formula on indicators and returns true whenever the formula returns true. 
#      Formula is the logical expression which you want to evaluate to generate a signal.


#   There are some other functions like sigPeak, sigTimestamp.




# Adding signals --------------------------------------------------------------------------------------------------

## long signal is generated when 

  # RSI is greater than 50 
  # MACD histogram crosses zero line for the first time.



# i. RSI_7 greater than 50
  # Using add.signal function add a signal RSI_gt_50 to the strategy which returns TRUE when 
  # rsi.RSI_7 is greater than 50. 
  # To generate the signal use sigThreshold function as we are comparing indicator to a threshold value.


add.signal(strategy.st, name = "sigThreshold", arguments = list(column = "rsi.RSI_7",threshold=50,relationship="gt"), 
           label = "RSI_gt_50")



# ii. macd histogram crosses zero line from below
  # MACD histogram is the difference between the macd line and the signal line, 
  # when macd histogram crosses zero line from below, macd line crosses the signal line from below 
  # and macd value will be greater than signal value.

# Using add.signal function 
# add a signal macd_gt_0 to the strategy which returns TRUE when macd.MACD crosses the signal.MACD. 
# relationship="gt" since we want the points where macd crosses the signal from below. 
# To generate the signal use sigCrossover function as we are comparing 2 indicators.


add.signal(strategy.st, name = "sigCrossover", arguments = list(columns = c("macd.MACD","signal.MACD"),
                                                                relationship="gt"), label = "macd_gt_0")

# iii. Generate a long signal
  # Using add.signal function add a signal Long to the strategy which returns TRUE when 
  # RSI_gt_50 & macd_gt_0 are True. To generate the signal use sigFormula function as we are evaluating a 
  # logical expression to generate a signal.


add.signal(strategy.st, name = "sigFormula",
           arguments = list(formula="RSI_gt_50 & macd_gt_0",
                            cross = FALSE), label = "Long")


# iv. RSI_7 less than 50
  # Using add.signal function add a signal RSI_lt_50 to the strategy which returns TRUE when rsi.RSI_7 is less than 50. 
  # To generate the signal use sigThreshold function as we are comparing indicator to a threshold value.


add.signal(strategy.st, name = "sigThreshold", arguments = list(column = "rsi.RSI_7",threshold=50,relationship="lt"), 
           label = "RSI_lt_50")

# v. macd histogram crosses zero line from above
  # MACD histogram is the difference between the macd line and the signal line, when macd histogram crosses zero line 
  # from above, macd line crosses the signal line from above and macd value will be less than signal value.

  # Using add.signal function add a signal macd_lt_0 to the strategy which returns TRUE when macd.MACD crosses 
  # the signal.MACD. relationship="lt" since we want the points where macd crosses the signal from above. 
  # To generate the signal use sigCrossover function as we are comparing 2 indicators.


add.signal(strategy.st, name = "sigCrossover", arguments = list(columns = c("macd.MACD","signal.MACD"),
                                                                relationship="lt"),cross=TRUE, label = "macd_lt_0")


# apply signals ---------------------------------------------------------------------------------------------------
# applySignals function in R is used to apply the signals to the strategy based on indicators. 
# The mktdata is the ouput data obtained after applying indicators to the strategy i.e., mktdata_ind in this case.


mktdata_sig <- applySignals(strategy=strategy.st,mktdata=mktdata_ind)
mktdata_sig[is.na(mktdata_sig)]=0
knitr::kable(tail(mktdata_sig))





